# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../billetes.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QWidget


class ui_sistemaPago(QWidget):

    def __init__(self):
        super().__init__()

        self.setupUi(self)

    def setupUi(self, sistemaPago):
        sistemaPago.setObjectName("sistemaPago")
        sistemaPago.resize(750, 384)
        sistemaPago.setMaximumSize(QtCore.QSize(1044, 788))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/moneda.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sistemaPago.setWindowIcon(icon)
        # sistemaPago.setWindowOpacity(1.0)
        sistemaPago.setStyleSheet("QWidget {\n"
                                  "background-color: #ffffff;\n"
                                  "}")
        self.lbl_billetes = QtWidgets.QLabel(sistemaPago)
        self.lbl_billetes.setGeometry(QtCore.QRect(140, 40, 141, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_billetes.sizePolicy().hasHeightForWidth())
        self.lbl_billetes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.lbl_billetes.setFont(font)
        self.lbl_billetes.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Mexico))
        self.lbl_billetes.setTextFormat(QtCore.Qt.RichText)
        self.lbl_billetes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_billetes.setObjectName("lbl_billetes")
        self.lbl_monedas = QtWidgets.QLabel(sistemaPago)
        self.lbl_monedas.setGeometry(QtCore.QRect(480, 40, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.lbl_monedas.setFont(font)
        self.lbl_monedas.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Mexico))
        self.lbl_monedas.setTextFormat(QtCore.Qt.RichText)
        self.lbl_monedas.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_monedas.setWordWrap(False)
        self.lbl_monedas.setObjectName("lbl_monedas")
        self.gridLayoutWidget = QtWidgets.QWidget(sistemaPago)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(460, 130, 200, 190))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/10.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 0, 2, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/5.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 1, 2, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(sistemaPago)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 110, 356, 221))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_20 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_20.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/20.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_20.setIcon(icon5)
        self.btn_20.setIconSize(QtCore.QSize(100, 100))
        self.btn_20.setFlat(True)
        self.btn_20.setObjectName("btn_20")
        self.gridLayout_2.addWidget(self.btn_20, 2, 4, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.btn_50 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_50.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/50.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_50.setIcon(icon6)
        self.btn_50.setIconSize(QtCore.QSize(100, 100))
        self.btn_50.setFlat(True)
        self.btn_50.setObjectName("btn_50")
        self.gridLayout_2.addWidget(self.btn_50, 2, 1, 1, 2)
        self.btn_100 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_100.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../images/100.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_100.setIcon(icon7)
        self.btn_100.setIconSize(QtCore.QSize(100, 100))
        self.btn_100.setFlat(True)
        self.btn_100.setObjectName("btn_100")
        self.gridLayout_2.addWidget(self.btn_100, 0, 5, 2, 2)
        self.btn_200 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_200.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../images/200.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_200.setIcon(icon8)
        self.btn_200.setIconSize(QtCore.QSize(100, 100))
        self.btn_200.setFlat(True)
        self.btn_200.setObjectName("btn_200")
        self.gridLayout_2.addWidget(self.btn_200, 0, 2, 2, 3)
        self.btn_500 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_500.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../images/500.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_500.setIcon(icon9)
        self.btn_500.setIconSize(QtCore.QSize(100, 100))
        self.btn_500.setFlat(True)
        self.btn_500.setObjectName("btn_500")
        self.gridLayout_2.addWidget(self.btn_500, 0, 0, 2, 2)

        self.retranslateUi(sistemaPago)
        QtCore.QMetaObject.connectSlotsByName(sistemaPago)
        self.show()

    def retranslateUi(self, sistemaPago):
        _translate = QtCore.QCoreApplication.translate
        sistemaPago.setWindowTitle(_translate("sistemaPago", "Dinero"))
        self.lbl_billetes.setText(_translate("sistemaPago", "Billetes"))
        self.lbl_monedas.setText(_translate("sistemaPago", "Monedas"))

# import ../imagenes_rc as imagenes_rc

if __name__ == '__main__':
    app = QApplication(sys.argv)
    x = ui_sistemaPago()
    sys.exit(app.exec_())
